### PR TITLE
Made jumping kinda work

### PR DESCRIPTION
**Pull request by reubenmiller98**

### CODE REVIEW

**Comment by danpprince** [comment]
What are the `PennyWumple` and `Sphere` prefabs? Do we need those or were they committed accidentally maybe?

**Comment by reubenmiller98** [comment]
Hey Dan,

They were prefabs for the projectile shooter thing I was messing with,
completely forgot to remove them when I committed, sorry about that!

Sincerely,
Reuben Miller
Junior Software Developer
(828) 242-2601
LinkedIn <https://www.linkedin.com/in/reuben-miller98/>

**Review by PatrickDolanJ — CHANGES_REQUESTED** [review]
:( miss ya

**Comment by danpprince** [comment]
Added jumping in https://github.com/danpprince/cave-game/pull/17 instead

RIP Reuben, hope to see ya soon

**Pull request closed without merging**
